---
title: "2_analyses_hormonal_data"
author: "Julie"
date: "20 November 2018"
output: html_document
---
# Analyses Alltag & Sex {.tabset}
## models with hormonal data 
```{r}
source("0_helpers.R")
library(knitr) # um diese dokumente zu generieren
library(formr) # formr paket, kann daten laden
opts_chunk$set(warning = F, message = F, fig.width = 10, fig.height = 10)
library(lubridate) # mit datum-uhrzeit rechnen
library(pander) # schoen formatierte tabellen
library(ggplot2)
library(tidyr) # daten von lang nach breit und zurueck
library(dplyr) # daten zusammenfassen etc. immer als letztes laden
library(lme4)
library(lmerTest)
library(effects)
library(apaTables)
load("cleaned_selected.rdata")
diary$premenstrual_phase_fab = factor(diary$premenstrual_phase_fab)
diary$hormonal_contraception = factor(diary$hormonal_contraception)
diary_social$premenstrual_phase_fab = factor(diary_social$premenstrual_phase_fab)
diary_social$hormonal_contraception = factor(diary_social$hormonal_contraception)
# diary = diary %>% filter(answered_honestly_today == 1)
# diary_social = diary_social %>% filter(answered_honestly_today == 1)

diary = diary %>% mutate(
  social_life_active_numeric = as.numeric(social_life_active),
  purposefully_met_people = if_else(social_life_active_numeric < 4, 0, 1),
  menstruation_labelled = relevel(menstruation_labelled, "no")
)

diary_social = diary_social %>% mutate(
  menstruation_labelled = relevel(menstruation_labelled, "no")
)

# diary %>% filter(included_d == T) %>% View()
# rmarkdown::render("2_analyses.Rmd", word_document())


library(broom.mixed)
library(brms)
library(bayesplot)
```

### time_family (hormonal data)
```{r}
model2_family_hormones <- brm(time_family ~ premenstrual_phase_fab + menstruation_labelled + hormonal_contraception * prc_stirn_b_LH + (1 | short ), data = diary %>% filter(included_d == T & abode_flat_share != 2 & relationship_status == 1), cores = 4)

#, file = "brms_fits/model2_family_hormones"

summary(model2_family_hormones)
stanplot(model2_family_hormones, pars = "^b_[^I]")
marginal_effects(model2_family_hormones)
hypothesis(model2_family_hormones, "prc_stirn_b_LH > 0")

tidy(model2_family_hormones) %>% select(term, estimate, conf.low, conf.high)
``` 

### contact with relatives
```{r}
model2_relatives <- brm(person_is_related_man ~ premenstrual_phase_fab + menstruation_labelled + hormonal_contraception * prc_stirn_b_LH + (1 | short / created_diary ), data = diary_social %>% filter(included_s == T  & abode_flat_share !=2), family = "bernoulli", cores = 4)
#, file = "brms_fits/model2_relatives"

summary(model2_relatives)
stanplot(model2_relatives, pars = "^b_[^I]")
marginal_effects(model2_relatives)
hypothesis(model2_relatives, "prc_stirn_b_LH > 0")
tidy(model2_relatives) %>% select(term, estimate, conf.low, conf.high)

``` 

### related men inferred
```{r}
model2_related_men_inferred <- brm(person_is_related_man_inferred ~ premenstrual_phase_fab + menstruation_labelled + hormonal_contraception * prc_stirn_b_LH + (1 | short / created_diary ), data=diary_social %>% filter(included_s == T  & abode_flat_share !=2), family = "bernoulli", cores = 4 )
#, file = "brms_fits/model2_related_men_inferred"

summary(model2_related_men_inferred)
stanplot(model2_related_men_inferred, pars = "^b_[^I]")
marginal_effects(model2_related_men_inferred)
hypothesis(model2_related_men_inferred, "prc_stirn_b_LH > 0")
tidy(model2_related_men_inferred) %>% select(term, estimate, conf.low, conf.high)
```

### relatives seen
```{r}
nrow(diary_social %>% filter(person_seen == T & included_s == T & abode_flat_share != 2 & person_is_related_man == T))

model2_relatives_seen <- brm(person_is_related_man ~ premenstrual_phase_fab + menstruation_labelled + hormonal_contraception * prc_stirn_b_LH + (1 | short / created_diary ), data = diary_social %>% filter(included_s == T  & abode_flat_share !=2 & person_seen == T), family = "bernoulli", cores = 4)
#, file = "brms_fits/model2_relatives_seen"

summary(model2_relatives_seen)
stanplot(model2_relatives_seen, pars = "^b_[^I]")
marginal_effects(model2_relatives_seen)
hypothesis(model2_relatives_seen, "prc_stirn_b_LH > 0")
tidy(model2_relatives_seen) %>% select(term, estimate, conf.low, conf.high)
```

### 2b relatives thought about 
```{r}
nrow(diary_social %>% filter(person_thought_about == T & included_s == T & abode_flat_share != 2 & person_is_related_man == T))

model2_social_life_related_thought_about <- brm(person_is_related_man ~ premenstrual_phase_fab + menstruation_labelled + hormonal_contraception * prc_stirn_b_LH + (1 | short / created_diary ), data = diary_social %>% filter(included_s == T  & abode_flat_share !=2 & person_thought_about == T), family = "bernoulli", cores = 4)
#, file = "brms_fits/model2_social_life_related_thought_about"

summary(model2_social_life_related_thought_about)
stanplot(model2_social_life_related_thought_about, pars = "^b_[^I]")
marginal_effects(model2_social_life_related_thought_about)
hypothesis(model2_social_life_related_thought_about, "prc_stirn_b_LH > 0")
tidy(model2_social_life_related_thought_about) %>% select(term, estimate, conf.low, conf.high)
```

