---
title: "3_robustness_test"
author: "Julie"
date: "22 November 2018"
output: html_document
---

# Robustness analyses {.tabset .tabset-sticky}

```{r echo=F, results='hide',message=F,warning=F, error=F}
# rmarkdown::render("3_robustness_analyses_new.Rmd", word_document())
source("0_helpers.R")
library(knitr) # um diese dokumente zu generieren
library(formr) # formr paket, kann daten laden
opts_chunk$set(warning = F, message = F)
library(lubridate) # mit datum-uhrzeit rechnen
library(pander) # schoen formatierte tabellen
library(ggplot2)
library(tidyr) # daten von lang nach breit und zurueck
library(dplyr) # daten zusammenfassen etc. immer als letztes laden
library(lme4)
library(brms)
library(effects)
load("cleaned_selected.rdata")
diary$premenstrual_phase_fab = factor(diary$premenstrual_phase_fab)
diary$hormonal_contraception = factor(diary$hormonal_contraception)
diary_social$premenstrual_phase_fab = factor(diary_social$premenstrual_phase_fab)
diary_social$hormonal_contraception = factor(diary_social$hormonal_contraception)
diary = diary %>% filter(included_d == T)
diary_social = diary_social %>% filter(included_s == T)
diary = diary %>% mutate(
  social_life_active_numeric = as.numeric(social_life_active),
  purposefully_met_people = if_else(social_life_active_numeric < 4, 0, 1),
  menstruation_labelled = relevel(menstruation_labelled, "no")
)

diary_social = diary_social %>% mutate(
  menstruation_labelled = relevel(menstruation_labelled, "no")
)

# diary = diary %>% filter(answered_honestly_today == 1)
# diary_social = diary_social %>% filter(answered_honestly_today == 1)
```

## time family
```{r mod_time_fam}
model <- brm(time_family ~ premenstrual_phase_fab + menstruation_labelled +  hormonal_contraception * fertile_fab + (1 | short ), data = diary, cores = 4, file = "brms_fits/model2_family_robustness")

do_model(model, diary)
```