```{r}
library(brms)
outcome_var <- model$formula[[1]][[2]]

smooths30 <- conditional_effects(model, 
      effects = "RCD_fab:hormonal_contraception",
      spaghetti = TRUE, resolution = 60, 
      nsamples = 100, dpars = "mu",
      re_formula = NA)

library(tidyverse)

smo_data <- attributes(smooths30$`RCD_fab:hormonal_contraception`)$spaghetti %>% 
  mutate(nohc = if_else(hormonal_contraception == TRUE, "0", "1")) %>% 
  arrange(nohc)

smo_diff <- full_join(
  smo_data %>% 
    filter(nohc == "1") %>%
    mutate(sample__ = str_split_fixed(sample__, "_", n = 2)[,1]),
  smo_data %>% 
    filter(nohc == "0") %>% 
    mutate(sample__ = str_split_fixed(sample__, "_", n = 2)[,1]),
  by = c("RCD_fab", "sample__"), 
  suffix = c("_nohc", "_hc")
  ) %>% 
    mutate(estimate__ = estimate___nohc - estimate___hc,
           nohc = "diff")

smo_data <- bind_rows(smo_data, smo_diff)

if(model$family$family %in% c("gaussian", "bernoulli")) {
  sd_fun <- sd
} else if (model$family$family == "poisson") {
  sd_fun = mean
} 
y_axes <- bind_rows(
  model$data %>% 
    mutate(nohc = if_else(hormonal_contraception == TRUE, "0", "1")) %>% 
    group_by(nohc) %>% 
    summarise(
      n_women = n_distinct(person),
      outcomemeanplus1sd = min(mean(!!outcome_var, na.rm = T) + sd_fun(!!outcome_var, na.rm = T), max(!!outcome_var, na.rm = T)),
      outcomemeanminus1sd = max(mean(!!outcome_var, na.rm = T) - sd_fun(!!outcome_var, na.rm = T), min(!!outcome_var, na.rm = T))),
  model$data %>% 
    summarise(
      outcomemeanplus1sd = 0 + sd_fun(!!outcome_var, na.rm = T),
      outcomemeanminus1sd = 0 - sd_fun(!!outcome_var, na.rm = T)) %>% 
    mutate(nohc = "diff")
)

smo_data <- smo_data %>% 
  left_join(y_axes)

smo_data <- smo_data %>% 
  mutate(nohc = fct_inorder(case_when(
    nohc == "1" ~ paste0("Cycling (n=", n_women, ")"),
    nohc == "0" ~ paste0("HC user (n=", n_women, ")"),
    nohc == "diff" ~ "Difference"
  )))
  
alphas <- diary %>% 
  ungroup() %>% 
  select(RCD_fab, prc_stirn_b_squished) %>% 
  mutate(RCD_fab = round(RCD_fab)) %>% 
  distinct()
```

```{r fig.width=8,fig.height=5}
ggplot(smo_data, aes(RCD_fab)) +
  # grow the Y axes to show mean±1SD
  geom_blank(aes(ymin = outcomemeanminus1sd, 
                 ymax = outcomemeanplus1sd)) +
  # show fertile window probabilities as BG color
  geom_rect(aes(xmin = RCD_fab, xmax = RCD_fab + 1,
                alpha = prc_stirn_b_squished), 
            ymin = -Inf, ymax = Inf, 
            fill = '#A45B9D', color = NA, 
            group = 1, data = alphas) +
  # vertical line at the est. day of ovulation
  geom_vline(xintercept = -14, linetype = 'dashed') +
  
  # draw samples from spline
  geom_line(aes(y = estimate__, colour = nohc, group = sample__), stat = 'identity', alpha = 0.08) +
  
  # color lines
  scale_color_manual("Contraception", 
                     values = c('black', 'red', "#4B7BB4"), 
                     guide = FALSE) +
  
  # make the alpha range fit the prc_stirn_b values
  scale_alpha(guide = F, range = c(0,0.58)) +
  
  # irrelevant when showing individual spline estimates
  # scale_fill_manual("Contraception", 
  #                   labels = c("0" = "HC user", "1" = "Cycling", "diff" = "Difference"), 
  #                   values = c("0" = 'black', '1' = 'red', "diff" = "#4B7BB4"), 
  #                   breaks = c("0", "1", "diff"), guide = FALSE) +
  
  # facet the plot by contraception 
  facet_wrap( ~ nohc, scales = "free_y", ncol = 3) +
  
  # fancy labelling for X axis
  scale_x_continuous("Days until next menstrual onset (standardized to 29-day cycle)", 
                     breaks = c(-29, -21, -14, -6,-5,-4,-3,-2, -1), 
                     labels = c("29", "22", "14\nest. ovulation", "6\n", "\n", "\n", "\n\npremens.", "\n", "1\n")) +
  
  # This variable comes from the function
  scale_y_continuous(outcome) +
  
  cowplot::theme_cowplot(font_size = 10, 
                         font_family = "Helvetica") +
  
  theme(strip.background = element_rect(fill = "#FFFFFF"),
        strip.text = element_text(size = 11))

ggsave(paste0("figures/",outcome, "_curve.png"), width = 6, height = 3)
ggsave(paste0("figures/",outcome, "_curve.pdf"), width = 6, height = 3)
```

