---
title: "_robustness_model_test"
author: "Julie"
date: "22 November 2018"
output: html_document
---
#### Model summary {.tabset}

##### Basic model
```{r echo=F, results='hide',message=F,warning=F, error=F}
library(effects); library(lme4); library(lmerTest); library(knitr); library(brms)

summary(model)
stanplot(model, pars = "^b_[^I]")
marginal_effects(model)
hypothesis(model, "fertile_fab > 0")
```

##### Moderation by pregnant trying


```{r}
add_mod_main = update.formula(formula(model), new = as.formula(. ~ . + pregnant_trying * hormonal_contraception)) # reorder so that the triptych looks nice

mod_main = brms::brm(formula = add_mod_main, data = diary, file="C:/Users/driebe1/Dropbox/Julie/single_preferences/brms_fits/model_robustness")

add_mod_formula = update.formula(
    update.formula(formula(model), new = . ~ . - hormonal_contraception * fertile_fab), 
    new = as.formula(. ~ . + pregnant_trying * hormonal_contraception * fertile_fab)) # reorder so that the triptych looks nice
with_mod = brms::brm(formula = add_mod_formula, data = diary, file="C:/Users/driebe1/Dropbox/Julie/single_preferences/brms_fits/pregnant_robustness")

summary(with_mod)
stanplot(model, pars = "^b_[^I]")

tidy(with_mod) %>% select(term, estimate, conf.low, conf.high)
```
